# Generated by Django 4.2.7 on 2025-05-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_enhance_calendar_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='temperature_unit',
        ),
    ]
